# Generated by Django 2.0.4 on 2018-04-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='dish_photos'),
        ),
    ]
